/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dao.ChiTietPhieuNhapHangDAO;
import dao.KhoHangDAO;
import dao.PhieuNhapHangDAO;
import dao.SanPhamDAO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import pojo.ChiTietPhieuNhapHang;
import pojo.KhoHang;
import pojo.MyCombobox;
import pojo.PhieuNhapHang;
import pojo.SanPham;

/**
 *
 * @author TSOIS
 */
public class ChiTietPhieuNhapHang_GUI extends javax.swing.JFrame {

    
    DefaultComboBoxModel sp;
    /**
     * Creates new form ChiTietPhieuNhapHang_GUI
     */
    public ChiTietPhieuNhapHang_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Chi Tiết Phiếu Nhập Hàng");
        hienthi();
        hienthiPNH();
        loadSanPham();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_return = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_soluong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_thanhtien = new javax.swing.JTextField();
        txt_mapn = new javax.swing.JTextField();
        txt_masp = new javax.swing.JTextField();
        cbb_masp = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_DanhSachCTPNH = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_DanhSachPhieuNhapHang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_return.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return_icon.png"))); // NOI18N
        btn_return.setText("Trở về");
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Chi Tiết Phiếu Nhập Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Mã Phiếu Nhập Hàng: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Mã sản phẩm:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Số lượng:");

        txt_soluong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Thành tiền:");

        txt_thanhtien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        txt_mapn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        txt_masp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        cbb_masp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbb_masp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_maspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_masp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbb_masp, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_mapn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_thanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_mapn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbb_masp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_masp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_thanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách Chi Tiết Phiếu Nhập Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb_DanhSachCTPNH.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tb_DanhSachCTPNH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_DanhSachCTPNH.setGridColor(new java.awt.Color(0, 0, 0));
        tb_DanhSachCTPNH.setRowHeight(40);
        tb_DanhSachCTPNH.setRowMargin(5);
        tb_DanhSachCTPNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DanhSachCTPNHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_DanhSachCTPNH);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        btn_them.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_icon.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_icon.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_sua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_icon.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CHI TIẾT PHIẾU NHẬP HÀNG");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách Phiếu Nhập Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb_DanhSachPhieuNhapHang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tb_DanhSachPhieuNhapHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_DanhSachPhieuNhapHang.setGridColor(new java.awt.Color(0, 0, 0));
        tb_DanhSachPhieuNhapHang.setRowHeight(40);
        tb_DanhSachPhieuNhapHang.setRowMargin(5);
        tb_DanhSachPhieuNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DanhSachPhieuNhapHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_DanhSachPhieuNhapHang);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(556, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(371, 371, 371))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(btn_return)))
                    .addContainerGap(862, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_return)
                    .addGap(32, 32, 32)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(187, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_returnActionPerformed

    private void tb_DanhSachCTPNHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DanhSachCTPNHMouseClicked
        // TODO add your handling code here:
        int row = tb_DanhSachCTPNH.getSelectedRow();
        txt_mapn.setText((String)String.valueOf(tb_DanhSachCTPNH.getValueAt(row, 0)));
        txt_masp.setText((String)String.valueOf(tb_DanhSachCTPNH.getValueAt(row, 1)));
        txt_soluong.setText(String.valueOf(tb_DanhSachCTPNH.getValueAt(row, 2)));
        txt_thanhtien.setText(String.valueOf(tb_DanhSachCTPNH.getValueAt(row, 3)));
    }//GEN-LAST:event_tb_DanhSachCTPNHMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        /*String maNCC = txt_mapnh.getText();
        String tenNCC = txt_tenncc.getText();
        String diachiNCC = txt_tongsl.getText();
        if(txt_mapnh.getText().isEmpty()||txt_tenncc.getText().isEmpty()||txt_tongsl.getText().isEmpty()){
            txt_mapnh.requestFocus();
            JOptionPane.showMessageDialog(this,"Không Được Để Trống Thông Tin","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
            return;
        }else if(NhaCungCapDAO.CheckMaNCC(maNCC)==true){
            JOptionPane.showMessageDialog(this,"Trùng Mã Nhà Cung Cấp rồi nha","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            NhaCungCap ncc = new NhaCungCap();
            ncc.setMaNhaCungCap(maNCC);
            ncc.setTenNhaCungCap(tenNCC);
            ncc.setDiaChiNhaCungCap(diachiNCC);
            NhaCungCapDAO.themNhaCungCap(ncc);
            hienthi();
            JOptionPane.showMessageDialog(this,"Thêm Nhà Cung Cấp Thành Công","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
        }*/
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        /*try {
            NhaCungCap ncc = new NhaCungCap();
            String maNCC = txt_mapnh.getText();
            boolean n = NhaCungCapDAO.deleteNhaCungCap(maNCC);
            if (n == true) {
                JOptionPane.showMessageDialog(this, "Xóa " + maNCC + " Thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Xóa " + maNCC + " Thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xung đột khóa ngoại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } finally {
            hienthi();
        }*/
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        /*try {
            NhaCungCap ncc = new NhaCungCap();
            ncc.setTenNhaCungCap(txt_tenncc.getText());
            ncc.setMaNhaCungCap(txt_diachincc.getText());
            ncc.setDiaChiNhaCungCap(txt_mancc.getText());
            boolean n = NhaCungCapDAO.updateNhaCungCap(ncc);
            if (n == true) {
                JOptionPane.showMessageDialog(this, "Sửa Nhà Cung Cấp" + txt_mancc.getText() + " Thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Nhà Cung Cấp " + txt_mancc.getText() + " Thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sửa thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } finally {
            hienthi();
        }*/

        /*try {
            NhaCungCap ncc = new NhaCungCap();
            ncc.setTenNhaCungCap(txt_tenncc.getText());
            ncc.setDiaChiNhaCungCap(txt_tongsl.getText());
            ncc.setMaNhaCungCap(txt_mapnh.getText());
            boolean n = NhaCungCapDAO.updateNhaCungCap(ncc);
            int row = tb_DanhSachPNH.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn Dòng Cần Sửa ");
                return;
            } else {
                if (n == true) {
                    JOptionPane.showMessageDialog(this, "Sửa Nhà Cung Cấp\t "  + txt_mapnh.getText() + " Thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa Nhà Cung Cấp\t "  + txt_mapnh.getText() + " Thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sửa Kho Hàng thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } finally {
            hienthi();
        }*/
    }//GEN-LAST:event_btn_suaActionPerformed

    private void cbb_maspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_maspActionPerformed
        // TODO add your handling code here:
        MyCombobox chon = (MyCombobox) sp.getSelectedItem();
        String maSP = chon.MaString();
        txt_masp.setText(maSP);
    }//GEN-LAST:event_cbb_maspActionPerformed

    private void tb_DanhSachPhieuNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DanhSachPhieuNhapHangMouseClicked
        // TODO add your handling code here:
        int row = tb_DanhSachPhieuNhapHang.getSelectedRow();
        txt_mapn.setText((String)(tb_DanhSachPhieuNhapHang.getValueAt(row, 0)));
    }//GEN-LAST:event_tb_DanhSachPhieuNhapHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietPhieuNhapHang_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_return;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbb_masp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_DanhSachCTPNH;
    private javax.swing.JTable tb_DanhSachPhieuNhapHang;
    private javax.swing.JTextField txt_mapn;
    private javax.swing.JTextField txt_masp;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextField txt_thanhtien;
    // End of variables declaration//GEN-END:variables

    private void hienthi() {
        String[] tieude = {"Mã Phiếu Nhập", "Mã Sản Phẩm", "Số lượng", "Thành tiền"};
        ArrayList<ChiTietPhieuNhapHang> dsChiTietPNH = ChiTietPhieuNhapHangDAO.LayDanhSachChiTietPhieuNhapHang();
        DefaultTableModel dtm = (DefaultTableModel)tb_DanhSachCTPNH.getModel();
        dtm.setColumnIdentifiers(tieude);
        dtm.setRowCount(0);
        for(ChiTietPhieuNhapHang chitpnh: dsChiTietPNH){
            Vector <Object>v=new Vector<Object>();
            v.add(chitpnh.getMaPNH());
            v.add(chitpnh.getMaSP());
            v.add(chitpnh.getSoLuong());
            v.add(chitpnh.getThanhTien());
            dtm.addRow(v);
        }
        tb_DanhSachCTPNH.setModel(dtm);
    }

    private void loadSanPham() {
        sp = (DefaultComboBoxModel) cbb_masp.getModel();
        ArrayList<SanPham> dsSP = SanPhamDAO.LayDanhSachSanPham();
        for (SanPham sap : dsSP) {
            MyCombobox v = new MyCombobox(sap.getMaSP(), sap.getTenSP());
            sp.addElement(v);
        }
    }

    private void hienthiPNH() {
        String[] tieude = {"Mã Phiếu Nhập", "Ngày nhập"};
        ArrayList<PhieuNhapHang> dsPNH = PhieuNhapHangDAO.LayDanhSachPhieuNhapHang();
        DefaultTableModel dtm = (DefaultTableModel)tb_DanhSachPhieuNhapHang.getModel();
        dtm.setColumnIdentifiers(tieude);
        dtm.setRowCount(0);
        for(PhieuNhapHang pnh: dsPNH){
            Vector <Object>v=new Vector<Object>();
            v.add(pnh.getMaPNH());
            v.add(pnh.getNgayNH());
            dtm.addRow(v);
        }
        tb_DanhSachPhieuNhapHang.setModel(dtm);
    }
}
