/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import bean.DanhMuc;
import controller.ChuyenTrang;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Quản lý siêu thị");
        ChuyenTrang controller = new ChuyenTrang(pn_Container);
        controller.setView(jpn_TrangChu,label_TrangChu);
        List<DanhMuc> listItem= new ArrayList<>();
        listItem.add(new DanhMuc("TrangChu",jpn_TrangChu,label_TrangChu));
        listItem.add(new DanhMuc("HoaDon",jpn_HoaDon,label_HoaDon));
        listItem.add(new DanhMuc("KhachHang",jpn_KhachHang,label_KhachHang));
        listItem.add(new DanhMuc("NhanVien",jpn_NhanVien,label_NhanVien));
        listItem.add(new DanhMuc("TaiKhoan",jpn_TaiKhoan,label_TaiKhoan));
        listItem.add(new DanhMuc("SanPham",jpn_SanPham,label_SanPham));
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Main = new javax.swing.JPanel();
        pn_slideMenu = new javax.swing.JPanel();
        label_exit = new javax.swing.JLabel();
        jpn_TrangChu = new javax.swing.JPanel();
        label_TrangChu = new javax.swing.JLabel();
        jpn_HoaDon = new javax.swing.JPanel();
        label_HoaDon = new javax.swing.JLabel();
        jpn_KhachHang = new javax.swing.JPanel();
        label_KhachHang = new javax.swing.JLabel();
        jpn_NhanVien = new javax.swing.JPanel();
        label_NhanVien = new javax.swing.JLabel();
        jpn_TaiKhoan = new javax.swing.JPanel();
        label_TaiKhoan = new javax.swing.JLabel();
        jpn_SanPham = new javax.swing.JPanel();
        label_SanPham = new javax.swing.JLabel();
        label_menuopen = new javax.swing.JLabel();
        pn_Container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        pn_Main.setBackground(new java.awt.Color(255, 255, 255));
        pn_Main.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pn_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_slideMenu.setBackground(new java.awt.Color(255, 255, 255));
        pn_slideMenu.setPreferredSize(new java.awt.Dimension(266, 1080));

        label_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/exit.png"))); // NOI18N
        label_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exitMouseClicked(evt);
            }
        });

        jpn_TrangChu.setBackground(new java.awt.Color(255, 255, 255));

        label_TrangChu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_TrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_TrangChu.setText("Trang Chủ");
        label_TrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_TrangChuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpn_TrangChuLayout = new javax.swing.GroupLayout(jpn_TrangChu);
        jpn_TrangChu.setLayout(jpn_TrangChuLayout);
        jpn_TrangChuLayout.setHorizontalGroup(
            jpn_TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_TrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        jpn_TrangChuLayout.setVerticalGroup(
            jpn_TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_TrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jpn_HoaDon.setBackground(new java.awt.Color(255, 255, 255));

        label_HoaDon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_HoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_HoaDon.setText("Hóa đơn");
        label_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_HoaDonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpn_HoaDonLayout = new javax.swing.GroupLayout(jpn_HoaDon);
        jpn_HoaDon.setLayout(jpn_HoaDonLayout);
        jpn_HoaDonLayout.setHorizontalGroup(
            jpn_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        jpn_HoaDonLayout.setVerticalGroup(
            jpn_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jpn_KhachHang.setBackground(new java.awt.Color(255, 255, 255));

        label_KhachHang.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_KhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_KhachHang.setText("Khách Hàng");
        label_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_KhachHangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpn_KhachHangLayout = new javax.swing.GroupLayout(jpn_KhachHang);
        jpn_KhachHang.setLayout(jpn_KhachHangLayout);
        jpn_KhachHangLayout.setHorizontalGroup(
            jpn_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        jpn_KhachHangLayout.setVerticalGroup(
            jpn_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jpn_NhanVien.setBackground(new java.awt.Color(255, 255, 255));

        label_NhanVien.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_NhanVien.setText("Nhân Viên");
        label_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_NhanVienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpn_NhanVienLayout = new javax.swing.GroupLayout(jpn_NhanVien);
        jpn_NhanVien.setLayout(jpn_NhanVienLayout);
        jpn_NhanVienLayout.setHorizontalGroup(
            jpn_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        jpn_NhanVienLayout.setVerticalGroup(
            jpn_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jpn_TaiKhoan.setBackground(new java.awt.Color(255, 255, 255));

        label_TaiKhoan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_TaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_TaiKhoan.setText("Phiếu nhập");
        label_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_TaiKhoanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpn_TaiKhoanLayout = new javax.swing.GroupLayout(jpn_TaiKhoan);
        jpn_TaiKhoan.setLayout(jpn_TaiKhoanLayout);
        jpn_TaiKhoanLayout.setHorizontalGroup(
            jpn_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        jpn_TaiKhoanLayout.setVerticalGroup(
            jpn_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jpn_SanPham.setBackground(new java.awt.Color(255, 255, 255));

        label_SanPham.setBackground(new java.awt.Color(255, 255, 255));
        label_SanPham.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_SanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_SanPham.setText("Sản Phẩm");
        label_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_SanPhamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpn_SanPhamLayout = new javax.swing.GroupLayout(jpn_SanPham);
        jpn_SanPham.setLayout(jpn_SanPhamLayout);
        jpn_SanPhamLayout.setHorizontalGroup(
            jpn_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpn_SanPhamLayout.setVerticalGroup(
            jpn_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_slideMenuLayout = new javax.swing.GroupLayout(pn_slideMenu);
        pn_slideMenu.setLayout(pn_slideMenuLayout);
        pn_slideMenuLayout.setHorizontalGroup(
            pn_slideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_slideMenuLayout.createSequentialGroup()
                .addGroup(pn_slideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpn_TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_slideMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pn_slideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_exit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpn_TaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pn_slideMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jpn_HoaDon, jpn_KhachHang, jpn_NhanVien, jpn_TaiKhoan, jpn_TrangChu});

        pn_slideMenuLayout.setVerticalGroup(
            pn_slideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_slideMenuLayout.createSequentialGroup()
                .addComponent(label_exit)
                .addGap(86, 86, 86)
                .addComponent(jpn_TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pn_slideMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jpn_HoaDon, jpn_KhachHang, jpn_NhanVien, jpn_TaiKhoan, jpn_TrangChu});

        pn_Main.add(pn_slideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 800));

        label_menuopen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/menu1.png"))); // NOI18N
        label_menuopen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_menuopenMouseClicked(evt);
            }
        });
        pn_Main.add(label_menuopen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        pn_Container.setBackground(new java.awt.Color(255, 255, 255));
        pn_Container.setLayout(new java.awt.CardLayout());
        pn_Main.add(pn_Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1920, 1030));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseClicked
        closeMenuBar();
    }//GEN-LAST:event_label_exitMouseClicked

    private void label_TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_TaiKhoanMouseClicked
      
              closeMenuBar();
    }//GEN-LAST:event_label_TaiKhoanMouseClicked

    private void label_TrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_TrangChuMouseClicked
          closeMenuBar();
    }//GEN-LAST:event_label_TrangChuMouseClicked

    private void label_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_NhanVienMouseClicked
        // TODO add your handling code here:
        closeMenuBar();
    }//GEN-LAST:event_label_NhanVienMouseClicked

    private void label_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_KhachHangMouseClicked
       closeMenuBar();
    }//GEN-LAST:event_label_KhachHangMouseClicked

    private void label_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_HoaDonMouseClicked
       closeMenuBar();
    }//GEN-LAST:event_label_HoaDonMouseClicked

    private void label_menuopenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_menuopenMouseClicked
        // TODO add your handling code here:
        openMenuBar();
    }//GEN-LAST:event_label_menuopenMouseClicked

    private void label_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_SanPhamMouseClicked
         closeMenuBar();
    }//GEN-LAST:event_label_SanPhamMouseClicked

    /**
     * @param args the command line arguments
     */
    //WIDTH:235
    //HEIGHT:600
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpn_HoaDon;
    private javax.swing.JPanel jpn_KhachHang;
    private javax.swing.JPanel jpn_NhanVien;
    private javax.swing.JPanel jpn_SanPham;
    private javax.swing.JPanel jpn_TaiKhoan;
    private javax.swing.JPanel jpn_TrangChu;
    private javax.swing.JLabel label_HoaDon;
    private javax.swing.JLabel label_KhachHang;
    private javax.swing.JLabel label_NhanVien;
    private javax.swing.JLabel label_SanPham;
    private javax.swing.JLabel label_TaiKhoan;
    private javax.swing.JLabel label_TrangChu;
    private javax.swing.JLabel label_exit;
    private javax.swing.JLabel label_menuopen;
    private javax.swing.JPanel pn_Container;
    private javax.swing.JPanel pn_Main;
    private javax.swing.JPanel pn_slideMenu;
    // End of variables declaration//GEN-END:variables

    public void openMenuBar() {
        int width=300;
        int height=1080;
        new Thread(new Runnable() {
            @Override
            public void run() {
                for(int i=0;i<width;i++)
                {
                    pn_slideMenu.setSize(i, height);
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
  

    public void closeMenuBar() {
          int width=300;
        int height=1080;
        new Thread(new Runnable() {
            @Override
            public void run() {
                for(int i=width;i>0;i--)
                {
                    pn_slideMenu.setSize(i, height);
                     try {
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
}
