/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dao.KhachHangDAO;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import pojo.KhachHang;

/**
 *
 * @author TSOIS
 */
public class KhachHang_GUI extends javax.swing.JPanel {

    /**
     * Creates new form KhachHang_GUI
     */
    public KhachHang_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Quản lý Khách Hàng");
        cbb_gioitinhkh.addItem("NAM");
        cbb_gioitinhkh.addItem("NỮ");
        cbb_gioitinhkh.addItem("KHÁC");
        rad_theoma.setSelected(true);
        this.setSize(1720, 830);
        DefaultTableModel dtm = (DefaultTableModel)tb_DanhsachKH.getModel();
        hienthi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_return = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_makh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_tenkh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_diachikh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_emailkh = new javax.swing.JTextField();
        txt_sdtkh = new javax.swing.JTextField();
        cbb_gioitinhkh = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        btn_timkiemtheoma = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        rad_theoma = new javax.swing.JRadioButton();
        rad_theoten = new javax.swing.JRadioButton();
        btn_sua = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_DanhsachKH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1920, 1030));

        btn_return.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return_icon.png"))); // NOI18N
        btn_return.setText("Trở về");
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Mã Khách Hàng: ");

        txt_makh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_makh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_makhActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Tên Khách Hàng: ");

        txt_tenkh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_tenkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenkhActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Địa chỉ Khách Hàng: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Giới tính:");

        txt_diachikh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_diachikh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diachikhActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Số điện thoại: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Email Khách Hàng:");

        txt_emailkh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_emailkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailkhActionPerformed(evt);
            }
        });

        txt_sdtkh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_sdtkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtkhActionPerformed(evt);
            }
        });

        cbb_gioitinhkh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbb_gioitinhkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_gioitinhkhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_tenkh, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(txt_makh)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_emailkh)
                            .addComponent(txt_diachikh)
                            .addComponent(txt_sdtkh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbb_gioitinhkh, 0, 310, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_diachikh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_gioitinhkh, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_sdtkh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_emailkh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N

        btn_them.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_icon.png"))); // NOI18N
        btn_them.setText("Thêm ");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_icon.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Vui lòng nhập:");

        txt_timkiem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemActionPerformed(evt);
            }
        });

        btn_timkiemtheoma.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_timkiemtheoma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N
        btn_timkiemtheoma.setText("Tìm kiếm");
        btn_timkiemtheoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemtheomaActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset_icon.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        buttonGroup1.add(rad_theoma);
        rad_theoma.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rad_theoma.setText("Tìm kiếm theo mã Khách Hàng");

        buttonGroup1.add(rad_theoten);
        rad_theoten.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rad_theoten.setText("Tìm kiếm theo tên Khách Hàng");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btn_timkiemtheoma)
                                .addGap(58, 58, 58)
                                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rad_theoma)
                            .addComponent(rad_theoten))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rad_theoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(rad_theoten)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_timkiemtheoma, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        btn_sua.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_icon.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb_DanhsachKH.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tb_DanhsachKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_DanhsachKH.setRowHeight(40);
        tb_DanhsachKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DanhsachKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_DanhsachKH);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_return)
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addContainerGap(1131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_return)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_returnActionPerformed

    private void txt_makhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_makhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_makhActionPerformed

    private void txt_tenkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenkhActionPerformed

    private void txt_diachikhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diachikhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diachikhActionPerformed

    private void txt_emailkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailkhActionPerformed

    private void txt_sdtkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtkhActionPerformed

    private void cbb_gioitinhkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_gioitinhkhActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbb_gioitinhkhActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String maKH = txt_makh.getText();
        String tenKH = txt_tenkh.getText();
        String diaChiKH = txt_diachikh.getText();
        String gioiTinhKH = (String) cbb_gioitinhkh.getSelectedItem();
        String sdtKH = txt_sdtkh.getText();
        String emailKH = txt_emailkh.getText();
        if(txt_makh.getText().isEmpty()||txt_tenkh.getText().isEmpty()||txt_diachikh.getText().isEmpty()||txt_emailkh.getText().isEmpty()){
            txt_makh.requestFocus();
            JOptionPane.showMessageDialog(this,"Không Được Để Trống Thông Tin","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
            return;
        }else if(KhachHangDAO.CheckMaKH(maKH)==true){
            JOptionPane.showMessageDialog(this,"Trùng Mã Khách Hàng rồi nha","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            KhachHang kh = new KhachHang();
            kh.setMa_KH(maKH);
            kh.setTenKH(tenKH);
            kh.setDiaChi(diaChiKH);
            kh.setGioiTinh(gioiTinhKH);
            kh.setSDT_KH(sdtKH);
            kh.setEmail_KH(emailKH);
            KhachHangDAO.themKhachHang(kh);
            hienthi();
            JOptionPane.showMessageDialog(this,"Thêm Khách Hàng Thành Công","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        try {
            KhachHang kh = new KhachHang();
            String maKH = txt_makh.getText();
            int row = tb_DanhsachKH.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn Dòng Cần Xóa ");
                return;
            } else {
                int m = JOptionPane.showConfirmDialog(this, "Bạn có thật sự muốn xóa  Khách Hàng \t "+ maKH +"  không ?" , "Thông báo", JOptionPane.YES_NO_OPTION);
                if(m == JOptionPane.NO_OPTION){
                    return;
                }else{
                    boolean n = KhachHangDAO.deleteKhachHang(maKH);
                    if (n == true) {
                        JOptionPane.showMessageDialog(this, "Xóa Khách Hàng\t " + maKH + " Thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Xóa Khách Hàng\t  " + maKH + " Thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xung đột khóa ngoại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } finally {
            hienthi();
        }

    }//GEN-LAST:event_btn_xoaActionPerformed

    private void txt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemActionPerformed

    private void btn_timkiemtheomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemtheomaActionPerformed
        // TODO add your handling code here:
        if(rad_theoma.isSelected()){

            DefaultTableModel dtm = (DefaultTableModel)tb_DanhsachKH.getModel();
            int count = 0;
            String maKH = txt_timkiem.getText();
            dtm.setRowCount(0);
            ArrayList<KhachHang> dsKH = KhachHangDAO.findKhachHangTheoMa(maKH);
            for (KhachHang pb : dsKH) {
                Vector<Object> v = new Vector<Object>();
                v.add(pb.getMa_KH());
                v.add(pb.getTenKH());
                v.add(pb.getDiaChi());
                v.add(pb.getGioiTinh());
                v.add(pb.getSDT_KH());
                v.add(pb.getEmail_KH());
                dtm.addRow(v);
                count++;
            }
            tb_DanhsachKH.setModel(dtm);
            JOptionPane.showMessageDialog(this, "Tìm kiếm thấy\t " + count + " người có mã " + maKH, "Thong bao", JOptionPane.INFORMATION_MESSAGE);
        }else{
            DefaultTableModel dtm = (DefaultTableModel)tb_DanhsachKH.getModel();
            int count = 0;
            String tenKH = txt_timkiem.getText();
            dtm.setRowCount(0);
            ArrayList<KhachHang> dsKH = KhachHangDAO.findKhachHangTheoTen(tenKH);
            for (KhachHang kh : dsKH) {
                Vector<Object> v = new Vector<Object>();
                v.add(kh.getMa_KH());
                v.add(kh.getTenKH());
                v.add(kh.getDiaChi());
                v.add(kh.getGioiTinh());
                v.add(kh.getSDT_KH());
                v.add(kh.getEmail_KH());
                dtm.addRow(v);
                count++;
            }
            tb_DanhsachKH.setModel(dtm);
            JOptionPane.showMessageDialog(this, "Tìm kiếm thấy\t " + count + " người có tên " + tenKH, "Thong bao", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btn_timkiemtheomaActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        hienthi();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        try {
            KhachHang kh = new KhachHang();
            kh.setTenKH(txt_tenkh.getText());
            kh.setDiaChi(txt_diachikh.getText());
            kh.setGioiTinh((String) cbb_gioitinhkh.getSelectedItem());
            kh.setSDT_KH((String)(txt_sdtkh.getText()));
            kh.setEmail_KH(txt_emailkh.getText());
            kh.setMa_KH(txt_makh.getText());
            boolean n = KhachHangDAO.updateKhachHang(kh);
            int row = tb_DanhsachKH.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn Dòng Cần Sửa ");
                return;
            } else {
                if (n == true) {
                    JOptionPane.showMessageDialog(this, "Sửa Khách Hàng\t "  + txt_makh.getText() + " Thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa Khách Hàng\t"  + txt_makh.getText() + " Thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sửa Khách Hàng thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } finally {
            hienthi();
        }

    }//GEN-LAST:event_btn_suaActionPerformed

    private void tb_DanhsachKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DanhsachKHMouseClicked
        // TODO add your handling code here:
        int row = tb_DanhsachKH.getSelectedRow();
        txt_makh.setText((String)tb_DanhsachKH.getValueAt(row, 0));
        txt_tenkh.setText((String)tb_DanhsachKH.getValueAt(row, 1));
        txt_diachikh.setText((String)tb_DanhsachKH.getValueAt(row, 2));
        cbb_gioitinhkh.setSelectedItem((String)tb_DanhsachKH.getValueAt(row, 3));
        txt_sdtkh.setText(String.valueOf(tb_DanhsachKH.getValueAt(row, 4)));
        txt_emailkh.setText((String)tb_DanhsachKH.getValueAt(row, 5));
    }//GEN-LAST:event_tb_DanhsachKHMouseClicked

    private void theater(){
        JTableHeader thead = tb_DanhsachKH.getTableHeader();
        thead.setForeground(Color.BLUE);
        thead.setFont(new Font("Tahoma", Font.BOLD, 18));
        
        TableColumn col1 = tb_DanhsachKH.getColumnModel().getColumn(0);
        col1.setPreferredWidth(100);
        TableColumn col2 = tb_DanhsachKH.getColumnModel().getColumn(1);
        col2.setPreferredWidth(100);
        TableColumn col3 = tb_DanhsachKH.getColumnModel().getColumn(2);
        col3.setPreferredWidth(100);
        TableColumn col4 = tb_DanhsachKH.getColumnModel().getColumn(3);
        col4.setPreferredWidth(100);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_return;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiemtheoma;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbb_gioitinhkh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rad_theoma;
    private javax.swing.JRadioButton rad_theoten;
    private javax.swing.JTable tb_DanhsachKH;
    private javax.swing.JTextField txt_diachikh;
    private javax.swing.JTextField txt_emailkh;
    private javax.swing.JTextField txt_makh;
    private javax.swing.JTextField txt_sdtkh;
    private javax.swing.JTextField txt_tenkh;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        
    }

    private void hienthi() {
        theater();
        String[] tieude = {"Mã Khách Hàng", "Tên Khách Hàng", "Địa chỉ", "Giới tính", "SĐT", "Email"};
        ArrayList<KhachHang> dsKH = KhachHangDAO.LayDanhSachKhachHang();
        DefaultTableModel dtm = (DefaultTableModel)tb_DanhsachKH.getModel();
        dtm.setColumnIdentifiers(tieude);
        dtm.setRowCount(0);
        for(KhachHang kh: dsKH){
            Vector <Object>v=new Vector<Object>();
            v.add(kh.getMa_KH());
            v.add(kh.getTenKH());
            v.add(kh.getDiaChi());
            v.add(kh.getGioiTinh());
            v.add(kh.getSDT_KH());
            v.add(kh.getEmail_KH());
            dtm.addRow(v);
        }
        tb_DanhsachKH.setModel(dtm);
    }

    private void setTitle(String quản_lý_Khách_Hàng) {
        
    }
}
