/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dao.SanPhamDAO;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import pojo.SanPham;
import pojo.NhaCungCap;
import pojo.KhoHang;
import pojo.LoaiSanPham;
import dao.LoaiSanPhamDAO;
import dao.NhaCungCapDAO;
import dao.KhoHangDAO;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import pojo.LoaiSanPham;
import pojo.MyCombobox;

/**
 *
 * @author TSOIS
 */
public class SanPham_GUI extends javax.swing.JPanel {

    /**
     * Creates new form SanPham_GUI
     */
    DefaultComboBoxModel lsp;
    DefaultComboBoxModel ncc;
    DefaultComboBoxModel kho;
    public SanPham_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("QUẢN LÝ SẢN PHẨM");
        hienthi();
        GUI.LoaiSanPham_GUI f = new GUI.LoaiSanPham_GUI();
        loadLoaiSanPham();
        loadNhaCungCap();
        loadKhoHang();
        this.setSize(1920, 1030);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_return = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        btn_xuatfileex = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        rad_theoma = new javax.swing.JRadioButton();
        rad_theoten = new javax.swing.JRadioButton();
        btn_reset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_DanhSachSanPham = new javax.swing.JTable();
        btn_ncc = new javax.swing.JButton();
        btn_kho = new javax.swing.JButton();
        btn_loaisanpham = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_masp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_tensp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jdate_sx = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jdate_hsd = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txt_soluong = new javax.swing.JTextField();
        txt_gia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghichu = new javax.swing.JTextArea();
        cbb_mancc = new javax.swing.JComboBox<>();
        cbb_maloai = new javax.swing.JComboBox<>();
        cbb_makho = new javax.swing.JComboBox<>();
        txt_maloaisp = new javax.swing.JTextField();
        txt_mancc = new javax.swing.JTextField();
        txt_makho = new javax.swing.JTextField();
        txt_ngaySX = new javax.swing.JTextField();
        txt_hsd = new javax.swing.JTextField();
        btn_ngaySX = new javax.swing.JButton();
        btn_hsd = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1332, 1030));

        btn_return.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return_icon.png"))); // NOI18N
        btn_return.setText("Trở về");
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        btn_them.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_icon.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_icon.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_sua.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_icon.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Vui lòng nhập: ");

        txt_timkiem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        btn_xuatfileex.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_xuatfileex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel_icon.png"))); // NOI18N
        btn_xuatfileex.setText("Xuất file Excel");
        btn_xuatfileex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xuatfileexActionPerformed(evt);
            }
        });

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        buttonGroup1.add(rad_theoma);
        rad_theoma.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rad_theoma.setText("Tìm kiếm theo mã Sản Phẩm");
        rad_theoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_theomaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rad_theoten);
        rad_theoten.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rad_theoten.setText("Tìm kiếm theo tên Sản Phẩm");

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset_icon.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rad_theoma)
                            .addComponent(rad_theoten)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(btn_xuatfileex)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btn_search)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rad_theoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(rad_theoten)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xuatfileex, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reset))
                .addGap(22, 22, 22))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb_DanhSachSanPham.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tb_DanhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_DanhSachSanPham.setRowHeight(40);
        tb_DanhSachSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DanhSachSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_DanhSachSanPham);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_ncc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_ncc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NCC_icon.png"))); // NOI18N
        btn_ncc.setText("Nhà Cung Cấp");
        btn_ncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nccActionPerformed(evt);
            }
        });

        btn_kho.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_kho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kho_icon.png"))); // NOI18N
        btn_kho.setText("Kho");
        btn_kho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khoActionPerformed(evt);
            }
        });

        btn_loaisanpham.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_loaisanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loai_icon.png"))); // NOI18N
        btn_loaisanpham.setText("Loại Sản Phẩm");
        btn_loaisanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loaisanphamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_kho, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(btn_loaisanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_loaisanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(btn_kho, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(400, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ SẢN PHẨM");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Mã Sản Phẩm: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Mã Nhà Cung Cấp: ");

        txt_masp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Tên Sản Phẩm:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Ngày sản xuất:");

        txt_tensp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Mã Loại:");

        jdate_sx.setDateFormatString("yyyy-MM-dd");
        jdate_sx.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Hạn sử dụng:");

        jdate_hsd.setDateFormatString("yyyy-MM-dd");
        jdate_hsd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Số lượng: ");

        txt_soluong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_soluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soluongActionPerformed(evt);
            }
        });

        txt_gia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Ghi chú:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Giá:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Mã Kho:");

        txt_ghichu.setColumns(20);
        txt_ghichu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_ghichu.setRows(5);
        jScrollPane2.setViewportView(txt_ghichu);

        cbb_mancc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbb_mancc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_manccActionPerformed(evt);
            }
        });

        cbb_maloai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbb_maloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_maloaiActionPerformed(evt);
            }
        });

        cbb_makho.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbb_makho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_makhoActionPerformed(evt);
            }
        });

        txt_maloaisp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        txt_mancc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        txt_makho.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        txt_ngaySX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        txt_hsd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        btn_ngaySX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_ngaySX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/time_icon.png"))); // NOI18N
        btn_ngaySX.setText("Ngày SX");
        btn_ngaySX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ngaySXActionPerformed(evt);
            }
        });

        btn_hsd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_hsd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/time_icon.png"))); // NOI18N
        btn_hsd.setText("HSD");
        btn_hsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hsdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_maloaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(92, 92, 92)
                                .addComponent(cbb_makho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_ngaySX, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                        .addComponent(btn_hsd, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jdate_hsd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_gia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_tensp)
                                    .addComponent(jdate_sx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_soluong)
                                    .addComponent(txt_masp)
                                    .addComponent(cbb_maloai, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbb_mancc, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(txt_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_ngaySX, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_makho, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_hsd, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txt_masp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbb_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tensp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5))
                    .addComponent(jdate_sx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_ngaySX, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ngaySX, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hsd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdate_hsd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_hsd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(67, 67, 67)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbb_maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maloaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_makho, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_makho, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_return)
                        .addGap(484, 484, 484)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_return, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(472, 472, 472))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_returnActionPerformed

    
    
    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String maSP = txt_masp.getText();
            String maNCC = txt_mancc.getText();
            String tenNV = txt_tensp.getText();
            String ngaySX = txt_ngaySX.getText();
            String hSD = txt_hsd.getText();
            String soLuong =txt_soluong.getText();
            String maLoai = txt_maloaisp.getText();
            String gia = txt_gia.getText();
            String ghiChu = txt_ghichu.getText();
            String maKho = txt_makho.getText();
        if(txt_masp.getText().isEmpty()||txt_mancc.getText().isEmpty()||txt_tensp.getText().isEmpty()||txt_ngaySX.getText().isEmpty()||txt_hsd.getText().isEmpty()||txt_soluong.getText().isEmpty()||txt_maloaisp.getText().isEmpty()||txt_gia.getText().isEmpty()||txt_ghichu.getText().isEmpty()||txt_makho.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Không Được Để Trống Thông Tin","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
            return;
        }else if(SanPhamDAO.CheckMaSanPham(maSP)==true){
            JOptionPane.showMessageDialog(this,"Trùng Mã Sản Phẩm rồi nha","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            SanPham sp = new SanPham();
            sp.setMaSP(maSP);
            sp.setMaNhaCungCap(tenNV);
            sp.setTenSP(tenNV);
            sp.setNgaySX(ngaySX);
            sp.sethSD(hSD);
            sp.setSoLuongSP(soLuong);
            sp.setMaLoai(maLoai);
            sp.setGiaSP(gia);
            sp.setGhiChuSP(ghiChu);
            sp.setMaKho(maKho);
            SanPhamDAO.themSanPham(sp);
            hienthi();
            JOptionPane.showMessageDialog(this,"Thêm Sản Phẩm Thành Công","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int row =tb_DanhSachSanPham.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this,"Chọn Dòng Cần Xóa ");
            return;
        }else{
            int n = JOptionPane.showConfirmDialog(this,"Thông Báo","Chắc Xóa Chưa",JOptionPane.YES_NO_OPTION);
            if(n==JOptionPane.NO_OPTION){
                return;
            }else{
                String ma = (String)tb_DanhSachSanPham.getValueAt(row, 0);
                SanPhamDAO.xoaSanPham(ma);
                hienthi();
                JOptionPane.showMessageDialog(this,"Xoá Thành Công","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        hienthi();
    }//GEN-LAST:event_btn_xoaActionPerformed

    public void openFile(String file){
        try{
            File path = new File(file);
            Desktop.getDesktop().open(path);
        }catch(IOException ioe){
            System.out.println(ioe);
        }
    }
    
    private void btn_xuatfileexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xuatfileexActionPerformed
        // TODO add your handling code here:
        /*ArrayList<NhanVien> dsNV = NhanVienDAO.LayDanhSachNhanVien();
        try{
            XSSFWorkbook wordbook = new XSSFWorkbook();
            // Create font
            XSSFFont font = wordbook.createFont();
            font.setFontName("Times New Roman");
            font.setBold(true);
            font.setFontHeightInPoints((short) 14); // font size
            font.setColor(IndexedColors.WHITE.getIndex()); // text color
            CellStyle cellStyle = wordbook.createCellStyle();
            cellStyle.setFont(font);
            cellStyle.setFillForegroundColor(IndexedColors.BLUE.getIndex());
            cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            cellStyle.setBorderBottom(BorderStyle.THIN);

            XSSFSheet sheet = wordbook.createSheet("Danh sách Nhân viên");
            XSSFRow row = null;
            Cell cell = null;
            row = sheet.createRow(3);
            cell=row.createCell(0, CellType.STRING);
            cell.setCellStyle(cellStyle);
            cell.setCellValue("Mã nhân viên");

            cell=row.createCell(1, CellType.STRING);
            cell.setCellStyle(cellStyle);
            cell.setCellValue("Họ tên nhân viên");

            cell=row.createCell(2, CellType.STRING);
            cell.setCellStyle(cellStyle);
            cell.setCellValue("Giới tính");

            cell=row.createCell(3, CellType.STRING);
            cell.setCellStyle(cellStyle);
            cell.setCellValue("Số điện thoại");

            cell=row.createCell(4, CellType.STRING);
            cell.setCellStyle(cellStyle);
            cell.setCellValue("Số CCCD");

            cell=row.createCell(5, CellType.STRING);
            cell.setCellStyle(cellStyle);
            cell.setCellValue("Địa chỉ nhà");

            cell=row.createCell(6, CellType.STRING);
            cell.setCellStyle(cellStyle);
            cell.setCellValue("Chức vụ");

            cell=row.createCell(7, CellType.STRING);
            cell.setCellStyle(cellStyle);
            cell.setCellValue("Mật khẩu");

            for (int i=0; i<dsNV.size();i++){
                NhanVien nv = dsNV.get(i);
                row = sheet.createRow(4+i);
                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue(dsNV.get(i).getMaNhanVien());

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(dsNV.get(i).getTenNhanVien());

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(dsNV.get(i).getGioiTinh());

                cell = row.createCell(3, CellType.NUMERIC);
                cell.setCellValue(dsNV.get(i).getSDT());

                cell = row.createCell(4, CellType.NUMERIC);
                cell.setCellValue(dsNV.get(i).getCCCD());

                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue(dsNV.get(i).getDiaChi());

                cell = row.createCell(6, CellType.STRING);
                cell.setCellValue(dsNV.get(i).getChucVu());

                cell = row.createCell(7, CellType.STRING);
                cell.setCellValue(dsNV.get(i).getMatKhau());

            }
            File f = new File("D://Cong Nghe Java//ABC//DanhSachNV.xlsx");

            try {
                FileOutputStream fis = new FileOutputStream(f);
                wordbook.write(fis);
                fis.close();
            }
            catch (FileNotFoundException ex) {
                ex.printStackTrace();
            }
            catch(IOException ex){
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "In thành công");

        }catch(ExceptionInInitializerError ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi mở file");
        }*/
        
        try{
           JFileChooser jFileChooser = new JFileChooser();
           jFileChooser.showSaveDialog(this);
           File saveFile = jFileChooser.getSelectedFile();
           
           if(saveFile != null){
               saveFile = new File(saveFile.toString()+".xlsx");
               Workbook wb = new XSSFWorkbook();
               Sheet sheet = wb.createSheet("Danh sách Sản Phẩm");
               
               Row rowCol = sheet.createRow(0);
               for(int i=0;i<tb_DanhSachSanPham.getColumnCount();i++){
                   Cell cell = rowCol.createCell(i);
                   cell.setCellValue(tb_DanhSachSanPham.getColumnName(i));
               }
               
               for(int j=0;j<tb_DanhSachSanPham.getRowCount();j++){
                   Row row = sheet.createRow(j+1);
                   for(int k=0;k<tb_DanhSachSanPham.getColumnCount();k++){
                       Cell cell = row.createCell(k);
                       if(tb_DanhSachSanPham.getValueAt(j, k)!=null){
                           cell.setCellValue(tb_DanhSachSanPham.getValueAt(j, k).toString());
                       }
                   }
               }
               FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
               wb.write(out);
               wb.close();
               out.close();
               openFile(saveFile.toString());
           }else{
               JOptionPane.showMessageDialog(null,"Lỗi xuất file");
           }
       }catch(FileNotFoundException e){
           System.out.println(e);
       }catch(IOException io){
           System.out.println(io);
       }
        
    }//GEN-LAST:event_btn_xuatfileexActionPerformed

    private void txt_soluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soluongActionPerformed

    private void cbb_manccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_manccActionPerformed
        // TODO add your handling code here:
        MyCombobox chon = (MyCombobox) ncc.getSelectedItem();
        String maNCC = chon.MaString();
        txt_mancc.setText(maNCC);
    }//GEN-LAST:event_cbb_manccActionPerformed

    private void cbb_maloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_maloaiActionPerformed
        // TODO add your handling code here:
        MyCombobox chon = (MyCombobox) lsp.getSelectedItem();
        String maLSP = chon.MaString();
        txt_maloaisp.setText(maLSP);
    }//GEN-LAST:event_cbb_maloaiActionPerformed

    private void cbb_makhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_makhoActionPerformed
        // TODO add your handling code here:
        MyCombobox chon = (MyCombobox) kho.getSelectedItem();
        String maKHO = chon.MaString();
        txt_makho.setText(maKHO);
    }//GEN-LAST:event_cbb_makhoActionPerformed

    private void btn_ngaySXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ngaySXActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String ngSX = formater.format(jdate_sx.getDate());
        txt_ngaySX.setText(ngSX);
    }//GEN-LAST:event_btn_ngaySXActionPerformed

    private void btn_hsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hsdActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String ngSX = formater.format(jdate_hsd.getDate());
        txt_hsd.setText(ngSX);
    }//GEN-LAST:event_btn_hsdActionPerformed

    private void tb_DanhSachSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DanhSachSanPhamMouseClicked
        // TODO add your handling code here:
        int row = tb_DanhSachSanPham.getSelectedRow();
        txt_masp.setText((String)tb_DanhSachSanPham.getValueAt(row, 0));
        txt_mancc.setText((String)String.valueOf(tb_DanhSachSanPham.getValueAt(row, 1)));
        txt_tensp.setText((String)tb_DanhSachSanPham.getValueAt(row, 2));
        txt_ngaySX.setText((String)tb_DanhSachSanPham.getValueAt(row, 3));
        txt_hsd.setText((String)tb_DanhSachSanPham.getValueAt(row, 4));
        txt_soluong.setText(String.valueOf(tb_DanhSachSanPham.getValueAt(row, 5)));
        txt_maloaisp.setText((String)String.valueOf(tb_DanhSachSanPham.getValueAt(row, 6)));
        txt_gia.setText((String)tb_DanhSachSanPham.getValueAt(row, 7));
        txt_ghichu.setText((String)tb_DanhSachSanPham.getValueAt(row, 8));
        txt_makho.setText((String)String.valueOf(tb_DanhSachSanPham.getValueAt(row, 9)));
    }//GEN-LAST:event_tb_DanhSachSanPhamMouseClicked

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        try {
            SanPham sp = new SanPham();
            sp .setMaNhaCungCap(txt_mancc.getText());
            sp .setTenSP(txt_tensp.getText());
            sp .setNgaySX(txt_ngaySX.getText());
            sp .sethSD(txt_hsd.getText());
            sp .setSoLuongSP(txt_soluong.getText());
            sp .setMaLoai(txt_maloaisp.getText());
            sp .setGiaSP(txt_gia.getText());
            sp .setGhiChuSP(txt_ghichu.getText());
            sp .setMaKho(txt_makho.getText());
            sp .setMaSP(txt_masp.getText());
            boolean n = SanPhamDAO.capNhatSanPham(sp);
            int row = tb_DanhSachSanPham.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn Dòng Cần Sửa ");
                return;
            } else {
                if (n == true) {
                    JOptionPane.showMessageDialog(this, "Sửa Sản Phẩm\t "  + txt_masp.getText() + " Thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa Sản Phẩm\t"  + txt_masp.getText() + " Thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sửa Sản Phẩm thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } finally {
            hienthi();
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_nccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nccActionPerformed
        new NCC_GUI().setVisible(true);
    }//GEN-LAST:event_btn_nccActionPerformed

    private void btn_khoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khoActionPerformed
        // TODO add your handling code here:
        new KhoHang_GUI().setVisible(true);
    }//GEN-LAST:event_btn_khoActionPerformed

    private void btn_loaisanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loaisanphamActionPerformed
        // TODO add your handling code here:
        new LoaiSanPham_GUI().setVisible(true);
    }//GEN-LAST:event_btn_loaisanphamActionPerformed

    private void rad_theomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_theomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_theomaActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        hienthi();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        if(rad_theoma.isSelected()){

            DefaultTableModel dtm = (DefaultTableModel)tb_DanhSachSanPham.getModel();
            int count = 0;
            String maSP = txt_timkiem.getText();
            dtm.setRowCount(0);
            ArrayList<SanPham> dsSP = SanPhamDAO.findSanPhamTheoMa(maSP);
            for (SanPham sp : dsSP) {
                Vector<Object> v = new Vector<Object>();
                v.add(sp.getMaSP());
                v.add(sp.getMaNhaCungCap());
                v.add(sp.getTenSP());
                v.add(sp.getNgaySX());
                v.add(sp.gethSD());
                v.add(sp.getSoLuongSP());
                v.add(sp.getMaLoai());
                v.add(sp.getGiaSP());
                v.add(sp.getGhiChuSP());
                v.add(sp.getMaKho());
                dtm.addRow(v);
                count++;
            }
            tb_DanhSachSanPham.setModel(dtm);
            JOptionPane.showMessageDialog(this, "Tìm kiếm thấy\t " + count + " Sản phẩm có mã " + maSP, "Thong bao", JOptionPane.INFORMATION_MESSAGE);
        }else{
            DefaultTableModel dtm = (DefaultTableModel)tb_DanhSachSanPham.getModel();
            int count = 0;
            String tenSP = txt_timkiem.getText();
            dtm.setRowCount(0);
            ArrayList<SanPham> dsSP = SanPhamDAO.findSanPhamTheoTen(tenSP);
            for (SanPham sp : dsSP) {
                Vector<Object> v = new Vector<Object>();
                v.add(sp.getMaSP());
                v.add(sp.getMaNhaCungCap());
                v.add(sp.getTenSP());
                v.add(sp.getNgaySX());
                v.add(sp.gethSD());
                v.add(sp.getSoLuongSP());
                v.add(sp.getMaLoai());
                v.add(sp.getGiaSP());
                v.add(sp.getGhiChuSP());
                v.add(sp.getMaKho());
                dtm.addRow(v);
                count++;
            }
            tb_DanhSachSanPham.setModel(dtm);
            JOptionPane.showMessageDialog(this, "Tìm kiếm thấy\t " + count + " Sản phẩm có tên " + tenSP, "Thong bao", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hsd;
    private javax.swing.JButton btn_kho;
    private javax.swing.JButton btn_loaisanpham;
    private javax.swing.JButton btn_ncc;
    private javax.swing.JButton btn_ngaySX;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_return;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton btn_xuatfileex;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbb_makho;
    private javax.swing.JComboBox<String> cbb_maloai;
    private javax.swing.JComboBox<String> cbb_mancc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdate_hsd;
    private com.toedter.calendar.JDateChooser jdate_sx;
    private javax.swing.JRadioButton rad_theoma;
    private javax.swing.JRadioButton rad_theoten;
    private javax.swing.JTable tb_DanhSachSanPham;
    private javax.swing.JTextArea txt_ghichu;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_hsd;
    private javax.swing.JTextField txt_makho;
    private javax.swing.JTextField txt_maloaisp;
    private javax.swing.JTextField txt_mancc;
    private javax.swing.JTextField txt_masp;
    private javax.swing.JTextField txt_ngaySX;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextField txt_tensp;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables

    private void loadKhoHang() {
        kho = (DefaultComboBoxModel) cbb_makho.getModel();
        ArrayList<KhoHang> dsKHO = KhoHangDAO.LayDanhSachKhoHang();
        for (KhoHang koh : dsKHO) {
            MyCombobox v = new MyCombobox(koh.getMaKho(), koh.getTenKho());
            kho.addElement(v);
        }
    }

    private void loadNhaCungCap() {
        ncc = (DefaultComboBoxModel) cbb_mancc.getModel();
        ArrayList<NhaCungCap> dsNCC = NhaCungCapDAO.LayDanhSachNhaCungCap();
        for (NhaCungCap nacc : dsNCC) {
            MyCombobox v = new MyCombobox(nacc.getMaNhaCungCap(), nacc.getTenNhaCungCap());
            ncc.addElement(v);
        }
    }

    private void loadLoaiSanPham() {
        lsp = (DefaultComboBoxModel) cbb_maloai.getModel();
        ArrayList<LoaiSanPham> dsSP = LoaiSanPhamDAO.LayDanhSachLoaiSanPham();
        for (LoaiSanPham losp : dsSP) {
            MyCombobox v = new MyCombobox(losp.getMaLoai(), losp.getTenLoai());
            lsp.addElement(v);
        }
    }

    private void hienthi() {
        String[] tieude = {"Mã Sản Phẩm", "Mã NCC", "Tên Sản Phẩm", "Ngày Sản Xuất", "Hạn Sử Dụng", "Số lượng", "Mã loại", "Giá", "Ghi chú", "Mã kho"};
        ArrayList<SanPham> dsSP = SanPhamDAO.LayDanhSachSanPham();
        theater();
        DefaultTableModel dtm = (DefaultTableModel)tb_DanhSachSanPham.getModel();
        dtm.setColumnIdentifiers(tieude);
        dtm.setRowCount(0);
        for(SanPham sp: dsSP){
            Vector <Object>v=new Vector<Object>();
            v.add(sp.getMaSP());
            v.add(sp.getMaNhaCungCap());
            v.add(sp.getTenSP());
            v.add(sp.getNgaySX());
            v.add(sp.gethSD());
            v.add(sp.getSoLuongSP());
            v.add(sp.getMaLoai());
            v.add(sp.getGiaSP());
            v.add(sp.getGhiChuSP());
            v.add(sp.getMaKho());
            dtm.addRow(v);
        }
        txt_makho.enable(false);
        txt_mancc.enable(false);
        txt_maloaisp.enable(false);
        tb_DanhSachSanPham.setModel(dtm);
    }

     private void theater(){
        JTableHeader thead = tb_DanhSachSanPham.getTableHeader();
        thead.setForeground(Color.BLUE);
        thead.setFont(new Font("Tahoma", Font.BOLD, 18));
        
        TableColumn col1 = tb_DanhSachSanPham.getColumnModel().getColumn(0);
        col1.setPreferredWidth(100);
        TableColumn col2 = tb_DanhSachSanPham.getColumnModel().getColumn(1);
        col2.setPreferredWidth(100);
        TableColumn col3 = tb_DanhSachSanPham.getColumnModel().getColumn(2);
        col3.setPreferredWidth(100);
        TableColumn col4 = tb_DanhSachSanPham.getColumnModel().getColumn(3);
        col4.setPreferredWidth(100);
        /*TableColumn col5 = tb_DanhSachSanPham.getColumnModel().getColumn(4);
        col5.setPreferredWidth(100);
        TableColumn col6 = tb_DanhSachSanPham.getColumnModel().getColumn(5);
        col6.setPreferredWidth(100);
        TableColumn col7 = tb_DanhSachSanPham.getColumnModel().getColumn(6);
        col7.setPreferredWidth(100);
        TableColumn col8= tb_DanhSachSanPham.getColumnModel().getColumn(7);
        col8.setPreferredWidth(100);
        TableColumn col9 = tb_DanhSachSanPham.getColumnModel().getColumn(8);
        col9.setPreferredWidth(100);*/
    }
    
    private void setTitle(String quản_lý_sản_phẩm) {
        
    }

    private void setLocationRelativeTo(Object object) {
        
    }
}
